### ISSUE TITLE
Things that can have metadata on them

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#79]
The current list of things in the grammar that can have metadata on them is:
```
( symbol
| collection
| set
| namespaced_map
| tag
| fn
| unquote
| unquote_splicing
```
It appears that there are more possibilities.  Additional examples for:
```
| conditional
| deref
| quote
| backtick
| var_quote
```
are respectively:
* https://github.com/cerner/clara-rules/blob/main/src/main/clojure/clara/rules/memory.cljc#L433
* https://github.com/datacrypt-project/hitchhiker-tree/blob/master/src/hitchhiker/outboard.clj#L123
* https://github.com/athos/Postmortem/blob/master/src/postmortem/instrument/cljs.cljc#L63
* https://github.com/amperity/sparkplug/blob/master/sparkplug-core/src/clojure/sparkplug/kryo.clj#L367-L368
* https://github.com/phillord/tawny-owl/blob/master/src/tawny/owl.clj#L1820-L1825

In this list, deref seems to be the most common, followed by quote, backtick, and conditional.  I only encountered one example for var-quote.

The [clojure.org metadata page](https://clojure.org/reference/metadata#_metadata_reader_macros) currently says:
> Note that metadata reader macros are applied at read-time, not at evaluation-time, and can only be used with values that support metadata, like symbols, vars, collections, sequences, namespaces, refs, atoms, agents, etc. Some important exceptions that don’t support metadata are strings, numbers, booleans, Java objects, keywords (these are cached and can be shared within the runtime), and deftypes (unless they explicitly implement clojure.lang.IMeta).

The "etc." part seems to be able to include a fair bit -- as long as it implements `clojure.lang.IMeta" I guess, and IIUC this is not something that one can necessarily tell in all cases without running the code.

I haven't gone through the grammar exhaustively to check for other possibilities so I suppose there could be more...

**Comment by carocad** [comment]
> The "etc." part seems to be able to include a fair bit -- as long as it implements `clojure.lang.IMeta" I guess, and IIUC this is not something that one can necessarily tell in all cases without running the code.

certainly, any Clojure type that implements IMeta can have metadata associated with the runtime instance. However, that doesn't mean that the way to declare that runtime instance would differ from the standard grammar. For example, if a `record` or `type` would implement `IMeta`, the way to use it would still be `^ ::hello (->MyRecord :a 1, :b 2)`. 

The intention of the grammar rule is not to find out all runtime objects that have metadata (since it is perfectly possible to attach metadata with other runtime functions), but rather to find places where metadata is declared statically.
